name: Build and Push Django docker image

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      # - name: Get folder
      #   working-directory: django-docker-demo
      #   run: |
      #     echo "Current working directory"
      #     pwd
      #     echo "Folders and files"
      #     ls
      - name: Set Lowercase Image name
        id: vars
        run: |
          IMAGE_NAME=ghcr.io/${GITHUB_ACTOR,,}/docker-hands-on
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        working-directory: django-docker-demo
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push image
        working-directory: django-docker-demo
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
